" Name:         autumn
" Description:  Template for dark colorscheme
" Author:       Thomas Crescenzi <trescenzi@gmail.com>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: Wed Aug 26 12:53:42 2020

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'autumn'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#2e2c28', '#cb6e2d', '#feb346', '#cdd3de',
        \ '#ede3c7', '#c03b22', '#d28f33', '#faba4b', '#8b993d', '#ee5921',
        \ '#bf3f52', '#ffeacc', '#ffa399', '#cfe6b8', '#d4b95e', '#527aa3']
  if has('nvim')
    let g:terminal_color_0 = '#2e2c28'
    let g:terminal_color_1 = '#cb6e2d'
    let g:terminal_color_2 = '#feb346'
    let g:terminal_color_3 = '#cdd3de'
    let g:terminal_color_4 = '#ede3c7'
    let g:terminal_color_5 = '#c03b22'
    let g:terminal_color_6 = '#d28f33'
    let g:terminal_color_7 = '#faba4b'
    let g:terminal_color_8 = '#8b993d'
    let g:terminal_color_9 = '#ee5921'
    let g:terminal_color_10 = '#bf3f52'
    let g:terminal_color_11 = '#ffeacc'
    let g:terminal_color_12 = '#ffa399'
    let g:terminal_color_13 = '#cfe6b8'
    let g:terminal_color_14 = '#d4b95e'
    let g:terminal_color_15 = '#527aa3'
  endif
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ede3c7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ede3c7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#ede3c7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#cfe6b8 guibg=#2e2c28 guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#ffeacc guibg=#2e2c28 guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#ffa399 guibg=#2e2c28 guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#8b993d guibg=#2e2c28 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#8b993d guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#cdd3de guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#c03b22 guibg=#2e2c28 guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#feb346 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#feb346 guibg=#2e2c28 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#cdd3de guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#cdd3de guibg=#ede3c7 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=reverse cterm=reverse
  hi PmenuThumb guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#ede3c7 guibg=#8b993d guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#cdd3de guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#c03b22 guibg=#2e2c28 guisp=#c03b22 gui=undercurl cterm=undercurl
  hi SpellCap guifg=#c03b22 guibg=#2e2c28 guisp=#c03b22 gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#c03b22 guibg=#2e2c28 guisp=#c03b22 gui=undercurl cterm=undercurl
  hi SpellRare guifg=#c03b22 guibg=#2e2c28 guisp=#c03b22 gui=undercurl cterm=undercurl
  hi StatusLine guifg=#2e2c28 guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#2e2c28 guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#2e2c28 guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#2e2c28 guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#2e2c28 guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#2e2c28 guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#cdd3de guibg=#cdd3de guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#ede3c7 guibg=#cb6e2d guisp=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=#ede3c7 guibg=#cb6e2d guisp=NONE gui=reverse cterm=reverse
  hi WarningMsg guifg=#c03b22 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#cdd3de guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#faba4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#c03b22 guibg=#2e2c28 guisp=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#cdd3de guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#cb6e2d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#c03b22 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#faba4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#bf3f52 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#2e2c28 guibg=#cfe6b8 guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#c03b22 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#faba4b guibg=#ffa399 guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ede3c7 guibg=#2e2c28 guisp=NONE gui=bold cterm=bold
  hi netrwPlain guifg=#cdd3de guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi netrwDir guifg=#8b993d guibg=#2e2c28 guisp=NONE gui=NONE cterm=NONE
  hi jsThis guifg=#c03b22 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsUndefined guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsNull guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsNan guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsSuper guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsPrototype guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFunction guifg=#c03b22 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalObjects guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsArrowFunction guifg=#c03b22 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi jsArrowFuncArgs guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFuncArgs guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFuncName guifg=#d28f33 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi jsFuncBlock guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFuncParens guifg=#c03b22 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi jsObjectProp guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsVariableDef guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObjectKey guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsParen guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsParenIfElse guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsParenRepeat guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsParenSwitch guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsParenCatch guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsBracket guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsBlockLabel guifg=#faba4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFunctionKey guifg=#c03b22 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsClassDefinition guifg=#faba4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsDot guifg=#ede3c7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsDestructuringBlock guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsSpreadExpression guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsSpreadOperator guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsModuleKeyword guifg=#faba4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObjectValue guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsTemplateString guifg=#faba4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsTemplateExpression guifg=#cb6e2d guibg=NONE guisp=NONE gui=italic cterm=italic
  hi jsTemplateBraces guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsClassMethodType guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxElement guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxTag guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxOpenTag guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxCloseTag guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxTagName guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxOpenPunct guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxClosePunct guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxBraces guifg=#cdd3de guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxAttrib guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxComponentName guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsxExpressionBlock guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssDefinition guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssClassName guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssIdentifier guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssTagName guifg=#d28f33 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssAttributeSelector guifg=#d4b95e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssPositioningProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssBoxProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssUIProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssUIProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssFlexibleBoxProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssMediaProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssFontProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssTextProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssBackgroundProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssInteractProp guifg=#8b993d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssCustomProp guifg=#ee5921 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssFunctionName guifg=#cdd3de guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssFunction guifg=#cdd3de guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi jsArrowFunction gui=NONE cterm=NONE
    hi jsFuncName gui=NONE cterm=NONE
    hi jsFuncParens gui=NONE cterm=NONE
    hi jsTemplateExpression gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=187 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=187 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=187 ctermbg=236 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=187 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=236 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=187 ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=187 ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=187 ctermbg=236 cterm=NONE
  hi CursorLineNr ctermfg=187 ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=151 ctermbg=236 cterm=reverse
  hi DiffChange ctermfg=223 ctermbg=236 cterm=reverse
  hi DiffDelete ctermfg=217 ctermbg=236 cterm=reverse
  hi DiffText ctermfg=100 ctermbg=236 cterm=bold,reverse
  hi Directory ctermfg=100 ctermbg=252 cterm=NONE
  hi EndOfBuffer ctermfg=252 ctermbg=236 cterm=NONE
  hi ErrorMsg ctermfg=160 ctermbg=236 cterm=reverse
  hi FoldColumn ctermfg=214 ctermbg=236 cterm=NONE
  hi Folded ctermfg=214 ctermbg=236 cterm=italic
  hi IncSearch ctermfg=187 ctermbg=236 cterm=reverse
  hi LineNr ctermfg=252 ctermbg=236 cterm=NONE
  hi MatchParen ctermfg=252 ctermbg=187 cterm=NONE
  hi ModeMsg ctermfg=187 ctermbg=236 cterm=NONE
  hi MoreMsg ctermfg=187 ctermbg=236 cterm=NONE
  hi NonText ctermfg=187 ctermbg=236 cterm=NONE
  hi Pmenu ctermfg=187 ctermbg=236 cterm=NONE
  hi PmenuSbar ctermfg=187 ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=187 ctermbg=236 cterm=reverse
  hi PmenuThumb ctermfg=187 ctermbg=236 cterm=NONE
  hi Question ctermfg=187 ctermbg=236 cterm=NONE
  hi Search ctermfg=187 ctermbg=100 cterm=NONE
  hi SignColumn ctermfg=252 ctermbg=236 cterm=NONE
  hi SpecialKey ctermfg=187 ctermbg=236 cterm=NONE
  hi SpellBad ctermfg=160 ctermbg=236 cterm=underline
  hi SpellCap ctermfg=160 ctermbg=236 cterm=underline
  hi SpellLocal ctermfg=160 ctermbg=236 cterm=underline
  hi SpellRare ctermfg=160 ctermbg=236 cterm=underline
  hi StatusLine ctermfg=236 ctermbg=252 cterm=NONE
  hi StatusLineNC ctermfg=236 ctermbg=252 cterm=NONE
  hi TabLine ctermfg=236 ctermbg=252 cterm=NONE
  hi TabLineFill ctermfg=236 ctermbg=252 cterm=NONE
  hi TabLineSel ctermfg=236 ctermbg=252 cterm=NONE
  hi Title ctermfg=236 ctermbg=252 cterm=NONE
  hi VertSplit ctermfg=252 ctermbg=252 cterm=NONE
  hi Visual ctermfg=187 ctermbg=166 cterm=reverse
  hi VisualNOS ctermfg=187 ctermbg=166 cterm=reverse
  hi WarningMsg ctermfg=160 ctermbg=236 cterm=NONE
  hi WildMenu ctermfg=187 ctermbg=236 cterm=NONE
  hi Comment ctermfg=252 ctermbg=NONE cterm=italic
  hi Constant ctermfg=214 ctermbg=NONE cterm=NONE
  hi String ctermfg=202 ctermbg=NONE cterm=NONE
  hi Character ctermfg=202 ctermbg=NONE cterm=NONE
  hi Error ctermfg=160 ctermbg=236 cterm=reverse
  hi Identifier ctermfg=172 ctermbg=NONE cterm=NONE
  hi Function ctermfg=100 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=252 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=166 ctermbg=NONE cterm=NONE
  hi Special ctermfg=100 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=100 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=160 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=214 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=161 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=236 ctermbg=151 cterm=NONE
  hi Type ctermfg=100 ctermbg=NONE cterm=NONE
  hi Label ctermfg=160 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=214 ctermbg=217 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=187 ctermbg=236 cterm=bold
  hi netrwPlain ctermfg=252 ctermbg=236 cterm=NONE
  hi netrwDir ctermfg=100 ctermbg=236 cterm=NONE
  hi jsThis ctermfg=160 ctermbg=NONE cterm=NONE
  hi jsUndefined ctermfg=202 ctermbg=NONE cterm=NONE
  hi jsNull ctermfg=202 ctermbg=NONE cterm=NONE
  hi jsNan ctermfg=202 ctermbg=NONE cterm=NONE
  hi jsSuper ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsPrototype ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=160 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=100 ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=100 ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=160 ctermbg=NONE cterm=italic
  hi jsArrowFuncArgs ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsFuncArgs ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsFuncName ctermfg=172 ctermbg=NONE cterm=italic
  hi jsFuncBlock ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsFuncParens ctermfg=160 ctermbg=NONE cterm=italic
  hi jsObjectProp ctermfg=202 ctermbg=NONE cterm=NONE
  hi jsVariableDef ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsObjectKey ctermfg=202 ctermbg=NONE cterm=NONE
  hi jsParen ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsParenIfElse ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsParenRepeat ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsParenSwitch ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsParenCatch ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsBracket ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsBlockLabel ctermfg=214 ctermbg=NONE cterm=NONE
  hi jsFunctionKey ctermfg=160 ctermbg=NONE cterm=NONE
  hi jsClassDefinition ctermfg=214 ctermbg=NONE cterm=NONE
  hi jsDot ctermfg=187 ctermbg=NONE cterm=NONE
  hi jsDestructuringBlock ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsSpreadExpression ctermfg=202 ctermbg=NONE cterm=NONE
  hi jsSpreadOperator ctermfg=100 ctermbg=NONE cterm=NONE
  hi jsModuleKeyword ctermfg=214 ctermbg=NONE cterm=NONE
  hi jsObjectValue ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsTemplateString ctermfg=214 ctermbg=NONE cterm=NONE
  hi jsTemplateExpression ctermfg=166 ctermbg=NONE cterm=italic
  hi jsTemplateBraces ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsClassMethodType ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxElement ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxTag ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxOpenTag ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxCloseTag ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxTagName ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxOpenPunct ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsxClosePunct ctermfg=179 ctermbg=NONE cterm=NONE
  hi jsxBraces ctermfg=252 ctermbg=NONE cterm=NONE
  hi jsxAttrib ctermfg=100 ctermbg=NONE cterm=NONE
  hi jsxComponentName ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsxExpressionBlock ctermfg=202 ctermbg=NONE cterm=NONE
  hi cssDefinition ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=172 ctermbg=NONE cterm=NONE
  hi cssIdentifier ctermfg=172 ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=172 ctermbg=NONE cterm=NONE
  hi cssAttributeSelector ctermfg=179 ctermbg=NONE cterm=NONE
  hi cssPositioningProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssBoxProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssUIProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssUIProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssFlexibleBoxProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssMediaProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssFontProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssTextProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssBackgroundProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssInteractProp ctermfg=100 ctermbg=NONE cterm=NONE
  hi cssCustomProp ctermfg=202 ctermbg=NONE cterm=NONE
  hi cssFunctionName ctermfg=252 ctermbg=NONE cterm=NONE
  hi cssFunction ctermfg=252 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi jsArrowFunction cterm=NONE
    hi jsFuncName cterm=NONE
    hi jsFuncParens cterm=NONE
    hi jsTemplateExpression cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Grey ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Grey ctermbg=Black cterm=NONE
    hi Terminal ctermfg=Grey ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Grey ctermbg=NONE cterm=NONE
  hi CursorColumn ctermfg=Grey ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=Grey ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=Grey ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=LightYellow ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffText ctermfg=LightGreen ctermbg=Black cterm=bold,reverse
  hi Directory ctermfg=LightGreen ctermbg=LightGrey cterm=NONE
  hi EndOfBuffer ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=LightRed ctermbg=Black cterm=reverse
  hi FoldColumn ctermfg=DarkYellow ctermbg=Black cterm=NONE
  hi Folded ctermfg=DarkYellow ctermbg=Black cterm=italic
  hi IncSearch ctermfg=Grey ctermbg=Black cterm=reverse
  hi LineNr ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi MatchParen ctermfg=LightGrey ctermbg=Grey cterm=NONE
  hi ModeMsg ctermfg=Grey ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=Grey ctermbg=Black cterm=NONE
  hi NonText ctermfg=Grey ctermbg=Black cterm=NONE
  hi Pmenu ctermfg=Grey ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=Grey ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=Grey ctermbg=Black cterm=reverse
  hi PmenuThumb ctermfg=Grey ctermbg=Black cterm=NONE
  hi Question ctermfg=Grey ctermbg=Black cterm=NONE
  hi Search ctermfg=Grey ctermbg=LightGreen cterm=NONE
  hi SignColumn ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=Grey ctermbg=Black cterm=NONE
  hi SpellBad ctermfg=LightRed ctermbg=Black cterm=underline
  hi SpellCap ctermfg=LightRed ctermbg=Black cterm=underline
  hi SpellLocal ctermfg=LightRed ctermbg=Black cterm=underline
  hi SpellRare ctermfg=LightRed ctermbg=Black cterm=underline
  hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Title ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi Visual ctermfg=Grey ctermbg=DarkGrey cterm=reverse
  hi VisualNOS ctermfg=Grey ctermbg=DarkGrey cterm=reverse
  hi WarningMsg ctermfg=LightRed ctermbg=Black cterm=NONE
  hi WildMenu ctermfg=Grey ctermbg=Black cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi String ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Character ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Error ctermfg=LightRed ctermbg=Black cterm=reverse
  hi Identifier ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi Function ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Tag ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=LightCyan ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Label ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=LightYellow ctermbg=DarkGreen cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=Grey ctermbg=Black cterm=bold
  hi netrwPlain ctermfg=LightGrey ctermbg=Black cterm=NONE
  hi netrwDir ctermfg=LightGreen ctermbg=Black cterm=NONE
  hi jsThis ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi jsUndefined ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsNull ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsNan ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsSuper ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsPrototype ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=LightRed ctermbg=NONE cterm=italic
  hi jsArrowFuncArgs ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsFuncArgs ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsFuncName ctermfg=lightgreen ctermbg=NONE cterm=italic
  hi jsFuncBlock ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsFuncParens ctermfg=LightRed ctermbg=NONE cterm=italic
  hi jsObjectProp ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsVariableDef ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsObjectKey ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsParen ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsParenIfElse ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsParenRepeat ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsParenSwitch ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsParenCatch ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsBracket ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsBlockLabel ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsFunctionKey ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi jsClassDefinition ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsDot ctermfg=Grey ctermbg=NONE cterm=NONE
  hi jsDestructuringBlock ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsSpreadExpression ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsSpreadOperator ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi jsModuleKeyword ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsObjectValue ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsTemplateString ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsTemplateExpression ctermfg=DarkGrey ctermbg=NONE cterm=italic
  hi jsTemplateBraces ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsClassMethodType ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxElement ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxTag ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxOpenTag ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxCloseTag ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxTagName ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxOpenPunct ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsxClosePunct ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi jsxBraces ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi jsxAttrib ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi jsxComponentName ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi jsxExpressionBlock ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi cssDefinition ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssClassName ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi cssIdentifier ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=lightgreen ctermbg=NONE cterm=NONE
  hi cssAttributeSelector ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi cssPositioningProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssBoxProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssUIProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssUIProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssFlexibleBoxProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssMediaProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssFontProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssTextProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssBackgroundProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssInteractProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssCustomProp ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi cssFunctionName ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi cssFunction ctermfg=LightGrey ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi jsArrowFunction cterm=NONE
    hi jsFuncName cterm=NONE
    hi jsFuncParens cterm=NONE
    hi jsTemplateExpression cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: brown         #2e2c28        ~         Black
" Color: brownorange   #cb6e2d        ~         DarkGrey
" Color: goldenrod     #feb346        ~         DarkYellow 
" Color: white         #ede3c7        ~         Grey
" Color: cream         #cdd3de        ~         LightGrey
" Color: red           #c03b22        ~         LightRed
" color: orange        #d28f33        ~         lightgreen
" Color: yellow        #faba4b        ~         LightYellow
" Color: green         #8b993d        ~         LightGreen
" Color: orangeyellow  #ee5921        ~         LightYellow
" Color: lightorange   #d4b95e        ~         LightYellow
" Color: highlighty    #ffeacc        ~         LightYellow
" Color: highlightr    #ffa399        ~         DarkGreen
" Color: highlightg    #cfe6b8        ~         DarkYellow
" Color: deepviolet    #bf3f52        ~         LightCyan
" Color: darkblue      #527aa3        ~         DarkMagenta
" Term colors: brown brownorange goldenrod cream white
" Term colors: red orange yellow green orangeyellow deepviolet
" Term colors: highlighty highlightr highlightg lightorange darkblue
" vim: et ts=2 sw=2
